<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://apache.org"
         xmlns:xsi="http://w3.org"
         xsi:schemaLocation="http://apache.org http://apache.org">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ragav</groupId>
    <artifactId>ragav-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <!-- Links to your repository folders -->
    <modules>
        <module>backend</module>
        <module>frontend</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- Global Node & NPM versions used by all modules -->
        <node.version>v20.11.0</node.version>
        <npm.version>10.2.4</npm.version>
        <frontend-maven-plugin.version>1.15.0</frontend-maven-plugin.version>
    </properties>
</project>
